### ISSUE TITLE
css 공통적인 스타일 분리

### ISSUE THREAD

**Issue by tjrehdrms123** [danmuge/HTML#4]
아래와 같이 사용될때 재사용성을 위해 
```css
.a{ display : inline-block; background-color: red; }
.b{ display : inline-block; background-color: blue; }
```

```html
<div classs="a"></div>
<div classs="b"></div>
```

이렇게 변경
```css
.box_inline_block{ display : inline-block; }
.bg_red { background-color: red; }
.bg_blue{ background-color: blue; }
```

```html
<div classs="box_inline_block bg_red"></div>
<div classs="box_inline_block bg_blue"></div>
```
